<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>bks</string>
		<string>ss</string>
	</array>
	<key>name</key>
	<string>Storyscript</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>comment</key>
			<string>COMMENT_LINE</string>
			<key>match</key>
			<string>\/\/.*</string>
			<key>name</key>
			<string>comment.line.double-slash.bks</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>(/\\*)</string>
			<key>comment</key>
			<string>COMMENT_BLOCK</string>
			<key>end</key>
			<string>(\\*/)</string>
			<key>name</key>
			<string>comment.block.bks</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>([\[@])(\b((?![0-9])[a-zA-Z0-9_]+))\b</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.tag.begin.bks</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.tag.bks</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>TAG_COMMAND</string>
			<key>end</key>
			<string>(\])|(?=\[)</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.tag.end.bks</string>
				</dict>
			</dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>entity.other.attribute-name.bks</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(\b((?![0-9])[a-zA-Z0-9_]+))((?=[= ])|\b)</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>constant.numeric.bks</string>
						</dict>
					</dict>
					<key>comment</key>
					<string>NUMBER</string>
					<key>match</key>
					<string>(\b=)([0-9]+)</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>constant.language.bks</string>
						</dict>
					</dict>
					<key>comment</key>
					<string>BOOLEAN</string>
					<key>match</key>
					<string>(\b=)((true)|(false))</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>(\b=)(")</string>
					<key>beginCaptures</key>
					<dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>string.quoted.double.bks</string>
						</dict>
					</dict>
					<key>comment</key>
					<string>STRING_QUOTED_DOUBLE</string>
					<key>end</key>
					<string>(")</string>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>string.quoted.double.bks</string>
						</dict>
					</dict>
					<key>patterns</key>
					<array>
						<dict>
							<key>match</key>
							<string>(.)</string>
							<key>name</key>
							<string>string.quoted.double.bks</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>(\b=)(')</string>
					<key>beginCaptures</key>
					<dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>string.quoted.single.bks</string>
						</dict>
					</dict>
					<key>comment</key>
					<string>STRING_QUOTED_SINGLE</string>
					<key>end</key>
					<string>(')</string>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>string.quoted.single.bks</string>
						</dict>
					</dict>
					<key>patterns</key>
					<array>
						<dict>
							<key>match</key>
							<string>(.)</string>
							<key>name</key>
							<string>string.quoted.single.bks</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<dict>
			<key>comment</key>
			<string>TEXT</string>
			<key>match</key>
			<string>.+?(?=[\[|@])</string>
			<key>name</key>
			<string>markup.raw.bks</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>(#)(\s*)((let|while|if|elseif|else|foreach|end)\b)*</string>
			<key>beginCaptures</key>
			<dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>keyword.control.bks</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>LOGICAL</string>
			<key>end</key>
			<string>($)</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>comment</key>
					<string>NUMBER</string>
					<key>match</key>
					<string>\b([0-9]+)\b</string>
					<key>name</key>
					<string>constant.numeric.bks</string>
				</dict>
				<dict>
					<key>comment</key>
					<string>BOOLEAN</string>
					<key>match</key>
					<string>((true)|(false))</string>
					<key>name</key>
					<string>constant.language.bks</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>\B(")</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>string.quoted.double.bks</string>
						</dict>
					</dict>
					<key>comment</key>
					<string>STRING_QUOTED_DOUBLE</string>
					<key>end</key>
					<string>(")\B</string>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>string.quoted.double.bks</string>
						</dict>
					</dict>
					<key>patterns</key>
					<array>
						<dict>
							<key>match</key>
							<string>(.)</string>
							<key>name</key>
							<string>string.quoted.double.bks</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>\B(')</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>string.quoted.single.bks</string>
						</dict>
					</dict>
					<key>comment</key>
					<string>STRING_QUOTED_SINGLE</string>
					<key>end</key>
					<string>(')\B</string>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>string.quoted.single.bks</string>
						</dict>
					</dict>
					<key>patterns</key>
					<array>
						<dict>
							<key>match</key>
							<string>(.)</string>
							<key>name</key>
							<string>string.quoted.single.bks</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>comment</key>
					<string>VARIABLE_SP</string>
					<key>match</key>
					<string>((\$|#)(?![0-9])[a-zA-Z0-9_]+)((?=[= &lt;&gt;+-\\*/^%])|\\b|$)</string>
					<key>name</key>
					<string>variable.parameter.bks</string>
				</dict>
				<dict>
					<key>comment</key>
					<string>VARIABLE</string>
					<key>match</key>
					<string>(((?![0-9])[a-zA-Z0-9_]+))((?=[= &lt;&gt;+-\\*/^%])|\\b|$)</string>
					<key>name</key>
					<string>variable.parameter.bks</string>
				</dict>
				<dict>
					<key>comment</key>
					<string>OPERATOR</string>
					<key>match</key>
					<string>(\+|\-|\*|\/|=|==|&gt;|&lt;|&gt;=|&lt;=)</string>
					<key>name</key>
					<string>keyword.operator.bks</string>
				</dict>
			</array>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.storyscript</string>
	<key>uuid</key>
	<string>8544eaea-0884-436b-8ecc-4a683eef1d2c</string>
</dict>
</plist>
